name: pdf_watermark_example
description: Demo for pdf_watermark.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  pdf_watermark:
    path: ../
  file_picker: ^13.1.0
  path_provider: ^2.1.6

flutter:
  uses-material-design: true

